config/routes.rb
Rails.application.routes.draw do
  	get 'welcome/index'

  	resources :articles do 
		resources :comments
  	end
	
	get 'data_table/', to: 'data_table#show'	
	resources :data_table do
		#resources :orders
	end


	get 'order_books/', to: 'order_books#show'	
	resources :order_books do
		resources :levels do 
			resources :orders 
		end
	end


  	root 'welcome#index'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

	def index
    	@articles = Article.all
  	end
	
	def show
    	@article = Article.find(params[:id])
  	end
	
	def new
		@article = Article.new
  	end

	def edit
  		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
		
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	private
  	def article_params
    	params.require(:article).permit(:title, :text)
  	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "error") %> prohibited
				this article from being saved:
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>

	<p>
		<%= form.label :Body %><br>
		<%= form.text_area :Body %>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %><%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<%= link_to 'New Article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
	  <td><%= link_to 'Show', article_path(article) %></td>
	  <td><%= link_to 'Edit', edit_article_path(article) %></td>
	  <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>